"""add terms and postings tables

Revision ID: b4f68b508605
Revises: 51c873733ea4
Create Date: 2026-07-17 09:14:44.051939

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b4f68b508605'
down_revision: Union[str, Sequence[str], None] = '51c873733ea4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('terms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_terms_text'), 'terms', ['text'], unique=True)
    op.create_table('postings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('term_id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('term_freq', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['term_id'], ['terms.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('term_id', 'document_id', name='uq_term_document')
    )
    op.create_index(op.f('ix_postings_document_id'), 'postings', ['document_id'], unique=False)
    op.create_index(op.f('ix_postings_term_id'), 'postings', ['term_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_postings_term_id'), table_name='postings')
    op.drop_index(op.f('ix_postings_document_id'), table_name='postings')
    op.drop_table('postings')
    op.drop_index(op.f('ix_terms_text'), table_name='terms')
    op.drop_table('terms')
    # ### end Alembic commands ###
