"""add token_count to documents, add index_metadata table

Revision ID: d37e652f90ce
Revises: b4f68b508605
Create Date: 2026-07-28 08:46:33.208297

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd37e652f90ce'
down_revision: Union[str, Sequence[str], None] = 'b4f68b508605'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('index_metadata',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('total_documents', sa.Integer(), nullable=False),
    sa.Column('avg_doc_length', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('documents', sa.Column('token_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'token_count')
    op.drop_table('index_metadata')
    # ### end Alembic commands ###
